[project]
name = "hippodetector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.0",
    "httpx[http2]>=0.27.0",
    "h2>=4.1.0",
    "pydantic>=2.0.0",
]
